version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:latest
    command: "nginx -g 'daemon off;'"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - json-server
      - lite-server

  json-server:
    restart: always
    build: 
      context: ./api
      dockerfile: ./api.Dockerfile
    volumes: 
      - ./api:/root
  
  lite-server:
    restart: always
    build: 
      context: ./dist
      dockerfile: ./lite.Dockerfile
    entrypoint: lite-server -c /root/bs-config.js
    volumes: 
      - ./dist:/root